module.exports = {
  'add-classname': require('./add-classname'),
  connect: require('./connect'),
  'connect-map-dispatch-to-props': require('./connect-map-dispatch-to-props'),
  'connect-map-state-to-props': require('./connect-map-state-to-props'),
  'connect-merge-props': require('./connect-merge-props'),
  'convert-to-arrow-component': require('./convert-to-arrow-component'),
  'convert-to-class-component': require('./convert-to-class-component'),
  'convert-to-function-component': require('./convert-to-function-component'),
  disconnect: require('./disconnect'),
  'disconnect-map-dispatch-to-props': require('./disconnect-map-dispatch-to-props'),
  'disconnect-map-state-to-props': require('./disconnect-map-state-to-props'),
  'disconnect-merge-props': require('./disconnect-merge-props'),
  'generate-prop-types': require('./generate-prop-types'),
  'move-default-props-and-prop-types-out-of-class': require('./move-default-props-and-prop-types-out-of-class'),
  'move-default-props-and-prop-types-to-class': require('./move-default-props-and-prop-types-to-class'),
  'sort-attributes': require('./sort-attributes'),
  'sort-imports': require('./sort-imports'),
  'toggle-component-type': require('./toggle-component-type'),
  'toggle-with-router-hoc': require('./toggle-with-router-hoc')
};
